/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.views;

import com.mycompany.dao.DAOLendings;
import com.mycompany.models.LendingsM;
import static com.mycompany.mylib.Dashboard.ShowJPanel;
import com.mycompany.mylib.Login;
import java.awt.*;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author joaop
 */
public class Lendings extends javax.swing.JPanel {

    /**
     * Creates new form Inicio
     */
    public Lendings() {
        initComponents();
        InitStyles();
    }

    private void InitStyles() {
        title.putClientProperty("FlatLaf.style", "font: bold $h1.regular.font; font-size: 20px;");
        title.setForeground(new Color(40, 42, 54));

        lblFunc.putClientProperty("FlatLaf.style", "font: light $h2.regular.font;");
        lblFunc.setForeground(new Color(40, 42, 54));

        lblCliente.putClientProperty("FlatLaf.style", "font: light $h2.regular.font;");
        lblCliente.setForeground(new Color(40, 42, 54));

        lblItem.putClientProperty("FlatLaf.style", "font: light $h2.regular.font;");
        lblItem.setForeground(new Color(40, 42, 54));

        txtCliente.putClientProperty("JTextField.placeholderText", "Insira o ID do Cliente.");
        txtItem.putClientProperty("JTextField.placeholderText", "Insira o ID do Item.");

        txtFunc.setText(String.valueOf(Login.getIdfuncionarioLogado()));

    }

private boolean validateFields() {
    String cliente = txtCliente.getText().trim();
    String item = txtItem.getText().trim();

    if (cliente.isEmpty() || !Pattern.matches("\\d+", cliente))/*verifica se contem string*/ {
        JOptionPane.showMessageDialog(this, "ID do Cliente inválido. Por favor, insira um ID válido.");
        return false;
    }

    if (item.isEmpty() || !Pattern.matches("\\d+", item)) {
        JOptionPane.showMessageDialog(this, "ID do Item inválido. Por favor, insira um ID válido.");
        return false;
    }

    DAOLendings daoLending = new DAOLendings();

    if (!daoLending.clienteExiste(Integer.parseInt(cliente))) {
        JOptionPane.showMessageDialog(this, "ID do Cliente não encontrado. Por favor, insira um ID válido.");
        return false;
    }

    //chamando o metodo de VerificarItem
 DAOLendings.ItemStatus status = daoLending.verificarItemDisponivel(Integer.parseInt(item));

    if (status == DAOLendings.ItemStatus.NOT_FOUND) {
        JOptionPane.showMessageDialog(this, "ID do Item não encontrado. Por favor, insira um ID válido.");
        return false;
    } else if (status == DAOLendings.ItemStatus.UNAVAILABLE) {
        JOptionPane.showMessageDialog(this, "Item indisponível. Por favor, escolha outro item.");
        return false;
    }

    return true;
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        title = new javax.swing.JLabel();
        txtFunc = new javax.swing.JTextField();
        lblCliente = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        Buttom = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        lblFunc = new javax.swing.JLabel();
        lblItem = new javax.swing.JLabel();
        txtItem = new javax.swing.JTextField();
        btTabela = new javax.swing.JButton();

        setBackground(new java.awt.Color(40, 42, 54));
        setMinimumSize(new java.awt.Dimension(738, 480));

        bg.setBackground(new java.awt.Color(255, 255, 255));

        jSeparator1.setBackground(new java.awt.Color(40, 42, 54));
        jSeparator1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator1.setMinimumSize(new java.awt.Dimension(500, 100));
        jSeparator1.setName(""); // NOI18N
        jSeparator1.setOpaque(true);
        jSeparator1.setPreferredSize(new java.awt.Dimension(500, 100));

        jSeparator2.setBackground(new java.awt.Color(40, 42, 54));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setOpaque(true);

        title.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        title.setText("REALIZAR EMPRÉSTIMO");

        txtFunc.setEditable(false);
        txtFunc.setBackground(new java.awt.Color(40, 40, 40));
        txtFunc.setForeground(new java.awt.Color(255, 255, 255));
        txtFunc.setDragEnabled(true);
        txtFunc.setSelectionColor(new java.awt.Color(255, 255, 255));
        txtFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFuncActionPerformed(evt);
            }
        });

        lblCliente.setText("ID do Cliente");

        txtCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteActionPerformed(evt);
            }
        });

        Buttom.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Buttom.setText("EMPRESTAR");
        Buttom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Buttom.setFocusable(false);
        Buttom.setHideActionText(true);
        Buttom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtomActionPerformed(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(40, 42, 54));
        jSeparator3.setOpaque(true);
        jSeparator3.setPreferredSize(new java.awt.Dimension(10, 3));

        lblFunc.setText("ID do Funcionário");

        lblItem.setText("ID do Item");

        txtItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtItemActionPerformed(evt);
            }
        });

        btTabela.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btTabela.setText("TABELA");
        btTabela.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btTabela.setFocusable(false);
        btTabela.setHideActionText(true);
        btTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTabelaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblCliente)
                                .addComponent(txtCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                                .addComponent(txtFunc))
                            .addComponent(lblFunc)))
                    .addComponent(title))
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblItem)
                            .addComponent(txtItem, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Buttom, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(188, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                                .addComponent(btTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(135, 135, 135))))))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(btTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(64, 64, 64)
                                        .addComponent(lblItem, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtItem, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(44, 44, 44)
                                        .addComponent(Buttom, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addGap(111, 111, 111)
                                        .addComponent(lblFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addGap(65, 65, 65)
                                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(123, Short.MAX_VALUE))))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(title)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFuncActionPerformed

    private void txtClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteActionPerformed

    private void ButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtomActionPerformed

        if (!validateFields()) {
            return;
        }

        LendingsM lending = new LendingsM();

        lending.setFuncionarioId(Integer.parseInt(txtFunc.getText()));
        lending.setClienteId(Integer.parseInt(txtCliente.getText()));
        lending.setItemId(Integer.parseInt(txtItem.getText()));
        lending.setDevolvido(0);

        DAOLendings daoLending = new DAOLendings();
        daoLending.emprestar(lending);

        LimparCampos();

    }//GEN-LAST:event_ButtomActionPerformed

    private void txtItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtItemActionPerformed

    private void btTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTabelaActionPerformed
        // TODO add your handling code here:
        ShowJPanel(new TbLendings());
    }//GEN-LAST:event_btTabelaActionPerformed

    public void LimparCampos() {
        txtCliente.setText("");
        txtItem.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buttom;
    private javax.swing.JPanel bg;
    private javax.swing.JButton btTabela;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblFunc;
    private javax.swing.JLabel lblItem;
    private javax.swing.JLabel title;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtFunc;
    private javax.swing.JTextField txtItem;
    // End of variables declaration//GEN-END:variables
}
