/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.views;

import com.mycompany.dao.DAOLendings;
import com.mycompany.models.LendingsM;
import static com.mycompany.mylib.Dashboard.ShowJPanel;
import com.mycompany.mylib.Login;
import com.mycompany.utilitarios.Utilitarios;
import java.awt.Color;

/**
 *
 * @author joaop
 */
public class UpReturns extends javax.swing.JPanel {

    LendingsM itemReturn;

    /**
     * Creates new form Inicio
     */
    public UpReturns(LendingsM item) {
        initComponents();
        itemReturn = item;
        InitStyles();
    }

    private void InitStyles() {
        title.putClientProperty("FlatLaf.style", "font: bold $h1.regular.font; font-size: 20px;");
        lblFunc.putClientProperty("FlatLaf.style", "font: light $h2.regular.font;");
        lblItem.putClientProperty("FlatLaf.style", "font: light $h2.regular.font;");
        lblCliente.putClientProperty("FlatLaf.style", "font: light $h2.regular.font;");
        lblEmprestimoId.putClientProperty("FlatLaf.style", "font: light $h2.regular.font;");

        if (itemReturn != null) {
            txtEmprestimoId.setText(String.valueOf(itemReturn.getId()));
            txtFunc.setText(String.valueOf(Login.getIdfuncionarioLogado()));
//          txtFunc.setText(String.valueOf(itemReturn.getFuncionarioId()));
            txtCliente.setText(String.valueOf(itemReturn.getClienteId()));
            txtItem.setText(String.valueOf(itemReturn.getItemId()));
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        title = new javax.swing.JLabel();
        lblFunc = new javax.swing.JLabel();
        txtFunc = new javax.swing.JTextField();
        lblCliente = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        lblItem = new javax.swing.JLabel();
        txtItem = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        Buttom = new javax.swing.JButton();
        btTabela = new javax.swing.JButton();
        lblEmprestimoId = new javax.swing.JLabel();
        txtEmprestimoId = new javax.swing.JTextField();

        setBackground(new java.awt.Color(40, 42, 54));
        setMinimumSize(new java.awt.Dimension(738, 480));

        bg.setBackground(new java.awt.Color(255, 255, 255));

        jSeparator1.setBackground(new java.awt.Color(40, 42, 54));
        jSeparator1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator1.setMinimumSize(new java.awt.Dimension(500, 100));
        jSeparator1.setName(""); // NOI18N
        jSeparator1.setOpaque(true);
        jSeparator1.setPreferredSize(new java.awt.Dimension(500, 100));

        jSeparator2.setBackground(new java.awt.Color(40, 42, 54));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setOpaque(true);

        title.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        title.setForeground(new java.awt.Color(40, 42, 54));
        title.setText("REALIZAR DEVOLUÇÃO");

        lblFunc.setForeground(new java.awt.Color(40, 42, 54));
        lblFunc.setText("ID do Funcionário");

        txtFunc.setEditable(false);
        txtFunc.setBackground(new java.awt.Color(40, 40, 40));
        txtFunc.setForeground(new java.awt.Color(255, 255, 255));
        txtFunc.setToolTipText("");
        txtFunc.setDragEnabled(true);
        txtFunc.setSelectionColor(new java.awt.Color(255, 255, 255));
        txtFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFuncActionPerformed(evt);
            }
        });

        lblCliente.setForeground(new java.awt.Color(40, 42, 54));
        lblCliente.setText("ID do Cliente");

        txtCliente.setEditable(false);
        txtCliente.setBackground(new java.awt.Color(40, 40, 40));
        txtCliente.setForeground(new java.awt.Color(255, 255, 255));
        txtCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteActionPerformed(evt);
            }
        });

        lblItem.setForeground(new java.awt.Color(40, 42, 54));
        lblItem.setText("ID do Item");

        txtItem.setEditable(false);
        txtItem.setBackground(new java.awt.Color(40, 40, 40));
        txtItem.setForeground(new java.awt.Color(255, 255, 255));
        txtItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtItemActionPerformed(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(40, 42, 54));
        jSeparator3.setOpaque(true);
        jSeparator3.setPreferredSize(new java.awt.Dimension(10, 3));

        Buttom.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Buttom.setText("DEVOLVER");
        Buttom.setBorderPainted(false);
        Buttom.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Buttom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtomActionPerformed(evt);
            }
        });

        btTabela.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btTabela.setText("TABELA");
        btTabela.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btTabela.setFocusable(false);
        btTabela.setHideActionText(true);
        btTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTabelaActionPerformed(evt);
            }
        });

        lblEmprestimoId.setForeground(new java.awt.Color(40, 42, 54));
        lblEmprestimoId.setText("ID do Empréstimo");

        txtEmprestimoId.setEditable(false);
        txtEmprestimoId.setBackground(new java.awt.Color(40, 40, 40));
        txtEmprestimoId.setForeground(new java.awt.Color(255, 255, 255));
        txtEmprestimoId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmprestimoIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFunc)
                            .addComponent(lblEmprestimoId)
                            .addComponent(txtEmprestimoId, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(65, 65, 65)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblItem)
                                        .addComponent(txtItem, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                                        .addComponent(lblCliente)
                                        .addComponent(txtCliente))
                                    .addComponent(Buttom, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                        .addComponent(btTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135))))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(title))
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(lblEmprestimoId, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmprestimoId, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblItem, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtItem, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Buttom, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(138, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFuncActionPerformed

    private void txtClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteActionPerformed

    private void txtItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtItemActionPerformed

    private void ButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtomActionPerformed

        LendingsM lending = new LendingsM();

        lending.setFuncionarioId(Integer.parseInt(txtFunc.getText()));
        lending.setClienteId(Integer.parseInt(txtCliente.getText()));
        lending.setItemId(Integer.parseInt(txtItem.getText()));
        lending.setDevolvido(1);

        DAOLendings daoItems = new DAOLendings();

        lending.setId(itemReturn.getId()); // Necessario pra pegar o Id selecioado e editar
        daoItems.devolver(lending);

        ShowJPanel(new TbReturns()); //volta a tela dos itens não devolvidos

    }//GEN-LAST:event_ButtomActionPerformed

    private void btTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTabelaActionPerformed
        // TODO add your handling code here:
        ShowJPanel(new TbReturns());
    }//GEN-LAST:event_btTabelaActionPerformed

    private void txtEmprestimoIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmprestimoIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmprestimoIdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buttom;
    private javax.swing.JPanel bg;
    private javax.swing.JButton btTabela;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblEmprestimoId;
    private javax.swing.JLabel lblFunc;
    private javax.swing.JLabel lblItem;
    private javax.swing.JLabel title;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtEmprestimoId;
    private javax.swing.JTextField txtFunc;
    private javax.swing.JTextField txtItem;
    // End of variables declaration//GEN-END:variables
}
